
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "3000:3000"
